// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "StutterKit",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "StutterKit",
            targets: ["AppModule"],
            bundleIdentifier: "tetul.stutterTest3",
            teamIdentifier: "55N9G92HC4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .tv),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .microphone(purposeString: "please")
            ],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .copy("MLFile/StutterDetector.mlmodelc")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)